name: Build ReaderChunks

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install dependencies
      run: npm ci

    # - name: Install react-native-pdf-lib
    #   run: npm install react-native-pdf-lib

    - name: Expo prebuild (Android)
      run: npx expo prebuild --platform android --clean

    - name: Build Android APK
      working-directory: android
      run: ./gradlew assembleRelease

    - name: Upload Android APK
      uses: actions/upload-artifact@v4
      with:
        name: ReaderChunks-Android
        path: android/app/build/outputs/apk/release/app-release.apk

  build-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    # - name: Install react-native-pdf-lib
    #   run: npm install react-native-pdf-lib

    - name: Install CocoaPods
      run: sudo gem install cocoapods

    - name: Expo prebuild (iOS)
      run: npx expo prebuild --platform ios --clean

    - name: Install iOS dependencies
      working-directory: ios
      run: pod install

    - name: Build iOS IPA
      working-directory: ios
      run: |
        xcodebuild -workspace ReaderChunks.xcworkspace \
        -scheme ReaderChunks \
        -configuration Release \
        -archivePath ReaderChunks.xcarchive \
        archive

        xcodebuild -exportArchive \
        -archivePath ReaderChunks.xcarchive \
        -exportPath . \
        -exportOptionsPlist exportOptions.plist

    - name: Upload iOS IPA
      uses: actions/upload-artifact@v4
      with:
        name: ReaderChunks-iOS
        path: ios/*.ipa